apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: dXNlcm5hbWU=  # Replace with base64 encoded PostgreSQL username
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # Replace with base64 encoded PostgreSQL password
  POSTGRES_DB: cHJvZHVjdF9kYg==  # Replace with base64 encoded PostgreSQL database name
